version: "3.9"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: test

  mscliente-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/test
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
